blueprint:
  name: Switch Tap Up 1x
  description: Turn on a light when switch tapped up 1x or turn up of already on.
  domain: automation
  input:
    switch_entity:
      name: Switch
      description: The Zooz Zen 21 Switch being used to trigger the automation
      selector: 
        entity:
          domain: switch
    light_target:
      name: Light
      description: The light that will be adjusted
      selector:
        target:
          entity:
            domain: light
    brightness_step_pct:
      name: Brightness Step
      description: The percentage by which the light brightness will be increased each time
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: percent

mode: single
#max_exceeded: silent
  
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: !input switch_entity
      scene_id: 2
      scene_data: 7680

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input light_target
            state: 'Off'
        sequence:
          - service: light.turn_on
            data: {}
            entity_id: !input light_target
      - conditions:
          - condition: state
            entity_id: !input light_target
            state: 'on'
        sequence:
          - service: light.turn_on
            data:
              brightness_step_pct: 10
            entity_id: !input light_target
    default: []
